// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FreeIPAService) DeepCopyInto(out *FreeIPAService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreeIPAService.
func (in *FreeIPAService) DeepCopy() *FreeIPAService {
	if in == nil {
		return nil
	}
	out := new(FreeIPAService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FreeIPAService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FreeIPAServiceList) DeepCopyInto(out *FreeIPAServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FreeIPAService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreeIPAServiceList.
func (in *FreeIPAServiceList) DeepCopy() *FreeIPAServiceList {
	if in == nil {
		return nil
	}
	out := new(FreeIPAServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FreeIPAServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FreeIPAServiceSpec) DeepCopyInto(out *FreeIPAServiceSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreeIPAServiceSpec.
func (in *FreeIPAServiceSpec) DeepCopy() *FreeIPAServiceSpec {
	if in == nil {
		return nil
	}
	out := new(FreeIPAServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FreeIPAServiceStatus) DeepCopyInto(out *FreeIPAServiceStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreeIPAServiceStatus.
func (in *FreeIPAServiceStatus) DeepCopy() *FreeIPAServiceStatus {
	if in == nil {
		return nil
	}
	out := new(FreeIPAServiceStatus)
	in.DeepCopyInto(out)
	return out
}
