apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeipa-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: freeipa-operator
  template:
    metadata:
      labels:
        name: freeipa-operator
    spec:
      serviceAccountName: freeipa-operator
      containers:
        - name: freeipa-operator
          image: quay.io/coglative/freeipa-operator:latest
          command:
          - freeipa-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "freeipa-operator"
